name: Docker Hub description update

on:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  hub:
    name: Docker Hub description update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: phpdaily/php
          readme-filepath: ./README.md
