name: PHP 7.4 - Nightly Builds

on:
  push:
    branches:
      - master
    paths:
      - '7.4-dev/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-alpine:
    name: Build Alpine images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine: ['alpine3.12', 'alpine3.13', 'alpine3.14']
        sapi: ['cli', 'fpm', 'zts']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "tag_generic_version=phpdaily/php:7.4" >> $GITHUB_ENV
        if: ${{ matrix.alpine == 'alpine3.14' && matrix.sapi == 'cli' }}
      - run: echo "tag_generic_platform=phpdaily/php:7.4-${{ matrix.alpine }}" >> $GITHUB_ENV
        if: ${{ matrix.sapi == 'cli' }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: 7.4-dev/${{ matrix.alpine }}/${{ matrix.sapi }}
          no-cache: true
          push: true
          tags: |
            phpdaily/php:7.4-${{ matrix.sapi }}-${{ matrix.alpine }}
            ${{ env.tag_generic_version }}
            ${{ env.tag_generic_platform }}

  build-ubuntu:
    name: Build Ubuntu images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu: ['buster']
        sapi: ['apache', 'cli', 'fpm', "zts"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "tag_generic_platform=phpdaily/php:7.4-${{ matrix.ubuntu }}" >> $GITHUB_ENV
        if: ${{ matrix.sapi == 'cli' }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: 7.4-dev/${{ matrix.ubuntu }}/${{ matrix.sapi }}
          no-cache: true
          push: true
          tags: |
            phpdaily/php:7.4-${{ matrix.sapi }}-${{ matrix.alpine }}
            ${{ env.tag_generic_platform }}
